### ISSUE TITLE
N-Gen Racing US works with the same trick as Rollcage - Stage 2! 

### ISSUE THREAD

**Issue by rsn8887** [wad11656/SetRegion-GUI#1]
I got N-Gen Racing US to work following exactly the same instructions as Rollcage - Stage 2:

- Create .bin single file image of game using for example imgburn
- Use SetRegion GUI on Windows to inject Jap region into game .bin file
- Convert .bin to psp format with psp2psx use Game ID SLPS 02191
- use cdda enabler plugin on PSP to enable CDDA music on this and other PS1 games that use redbook audio tracks

Maybe these news can be added to the compatibility list? 

![1E8E60CB-961E-449A-95E3-EB40CA50DEA9](https://user-images.githubusercontent.com/13071547/190914439-1321301b-02c2-46ff-b018-224d4fae6e0f.jpeg)

**Comment by wad11656** [comment]
Awesome, added. Thanks so much!
